plugin:
    has_options: true
    icon: cobra_icon.png

    resources:
        - class: JrmUnamur\CobraBundle\Entity\CobraViewer
          name: unamur_cobra_viewer
          is_exportable: false
          icon: cobra_icon.png